# Generated by Django 5.0.3 on 2024-03-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "aplicacion4",
            "0002_consola_delete_estudiante_alter_profesor_apellido_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Juego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                ("consola", models.CharField(max_length=60)),
                ("stock", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("tiempo", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Curso",
        ),
        migrations.DeleteModel(
            name="Entregable",
        ),
        migrations.DeleteModel(
            name="Profesor",
        ),
    ]
