# Generated by Django 5.0.3 on 2024-03-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aplicacion4", "0003_juego_servicio_delete_curso_delete_entregable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                ("apellido", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
