# Generated by Django 5.0.3 on 2024-03-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aplicacion4", "0004_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="tiempo",
            field=models.CharField(max_length=40),
        ),
    ]
